language: rust
sudo: false
matrix:
  include:
    - rust: 1.24.0
    - name: Rust stable
      rust: stable
      before_script:
        - rustup component add rustfmt
        - cargo fmt -- --check
    - rust: beta
    - rust: nightly
      env:
       - BENCH=1
branches:
  only:
    - master
    # bors branches
    - staging
    - trying
script:
  - |
      cargo build --verbose --no-default-features &&
      cargo build --verbose --features "$FEATURES" &&
      cargo test --verbose --features "$FEATURES" &&
      ([ "$BENCH" != 1 ] || cargo bench --verbose --features "$FEATURES")
