language: rust
rust:
  - 1.32.0
  - stable
  - beta
  - nightly
branches:
  only:
    - master
    # bors branches
    - staging
    - trying
stages:
  - build
  - test
#  - clippy
#  - fmt
jobs:
  include:
    - stage: build
      script:
        - cargo build --verbose --no-default-features &&
        - cargo build --verbose --features "$FEATURES" &&
        - cargo bench --no-run --verbose --features "$FEATURES"
    - stage: test
      rust: nightly
      script:
        - cargo test --verbose --features "$FEATURES" &&
